site_name: Docs | Smart Home Server by ei23.de
site_url: https://ei23.de
site_author: Felix Grave
site_description: >-
  DIY Smart Home

nav:
  - Smart Home Server:
    - Los gehts: index.md
    - Installation & erster Start: start/install.md
    - Programme installieren & anpassen (Docker-Compose): start/docker-compose.md
    - Shortcuts: start/shortcuts.md
    - ei23 Dashboard anpassen: start/ei23-dashboard.md
    - Fernzugriff: start/remote-access.md
    - Sicherheit & Monitoring: start/security-monitoring.md
    - Backup & Restore: start/backuprestore.md
    - Akzeptanz der Mitbewohner: start/acceptance.md
    - Häufige Fragen (FAQ): start/faq.md
    - Weitere Fragen?: 'https://ei23.de/donate'
  - Software:
    - ESPHome: software/esphome.md
    - Grafana: software/grafana.md
    - Home Assinstant: software/homeassistant.md
    - InfluxDB: software/influx.md
    - Logitech-Media-Server: software/lms.md
    - MQTT-Explorer: software/mqttexplorer.md
    - Nextcloud: software/nextcloud.md
    - NodeRED: software/nodered.md
    - PaperlessNGX: software/paperlessngx.md
    - Traefik: software/traefik.md
    - Überblick: software/overview.md
    - Uptime Kuma: software/uptimekuma.md
    - Vaultwarden/Bitwarden: software/vaultwarden.md
    - VSCode: software/vscode.md
    - WireguardVPN: software/wireguard.md
  - Hardware:
    - Struktur: hardware/structure.md
    - Server: hardware/server.md
    - Edge Devices: hardware/edge-devices.md

repo_name: ei23com/diy-smart-home
repo_url: https://github.com/ei23com/diy-smart-home
copyright: by ei23.de

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

theme:
  name: material
  language: de
  logo: media/ei23.svg
  favicon: media/favicon.png
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - announce.dismiss
    - content.code.copy
    - content.code.annotate 
    - navigation.tabs
    - navigation.instant
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    
  font: 
    text: Karla
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

plugins:
  - privacy
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  # - offline

extra_javascript:
  - js/matomo.js

extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://ei23.de'
    - icon: fontawesome/brands/youtube
      link: 'https://youtube.com/ei23-de'
    - icon: fontawesome/brands/github
      link: 'https://github.com/ei23com/diy-smart-home'
    - icon: fontawesome/brands/reddit
      link: 'https://www.reddit.com/r/ei23/'
    - icon: fontawesome/brands/discord
      link: 'https://discord.gg/g88dNZq2'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/ei23de'